
namespace ErrorManagement.Auth.Application.Login;

// Handler generates the tokens internally
// to set cookies and build the HTTP response body
public record LoginResponse(
    string DisplayName,
    IReadOnlyList<string> Permissions,
    string AccessToken,         // generated by IJwtTokenService inside handler
    int ExpiresInSeconds);